# Generated by Django 4.1.1 on 2022-10-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_student_sco'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='C_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
