# Generated by Django 4.1.1 on 2022-10-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_company_c_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='C_email',
        ),
        migrations.AlterField(
            model_name='student',
            name='S_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_geneder',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_prn',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='compper',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_Name', models.CharField(max_length=50)),
                ('P_fname', models.CharField(max_length=50)),
                ('P_lname', models.CharField(max_length=50)),
                ('P_email', models.CharField(max_length=70)),
                ('P_pnol', models.CharField(max_length=11)),
                ('P_gender', models.CharField(max_length=1)),
                ('PC', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.company')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='SC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.compper'),
        ),
    ]
