# Generated by Django 4.1.1 on 2022-11-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_cendterm_id_remove_cmideterm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mideterm',
            name='id',
        ),
        migrations.AlterField(
            model_name='cendterm',
            name='C_SE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='management.student'),
        ),
        migrations.AlterField(
            model_name='cmideterm',
            name='C_SM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='management.student'),
        ),
        migrations.AlterField(
            model_name='endterm',
            name='SE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='management.student'),
        ),
        migrations.AlterField(
            model_name='mideterm',
            name='SM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='management.student'),
        ),
    ]
